[project]
name = "qwen-asr-onnx"
version = "0.1.0"
description = ""
authors = [
    {name = "wcy",email = "wcy@gmail.com"},
    {name = "wcw",email = "1695587905@qq.com"}
]
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    "librosa",
    "sox",
    "tokenizers",
    "grpcio (>=1.78.0,<2.0.0)",
    "protobuf (>=6.33.5,<7.0.0)",
    "typer (>=0.24.0,<0.25.0)",
    "omegaconf (>=2.3.0,<3.0.0)",
    "onnxruntime (<1.24)",
    "huggingface-hub (>=0.34.0,<1.0)",
    "numpy (<2.3)",
    "ml-dtypes (>=0.6.0,<0.7.0)",
    "cffi (>=2.1.1,<3.0.0)",
    "scipy (==1.14.1)",
    "soundfile (>=0.14.0,<0.15.0)",
    "transformers (==4.57.6)"
]

[[tool.poetry.source]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "primary"

[tool.poetry]
packages = [{include = "qwen_asr_onnx", from = "src"}]

[tool.poetry.group.dev.dependencies]
pytest = ">=8.3,<9"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
