FROM registry.cn-hangzhou.aliyuncs.com/migo-dl/axengine:0.1.3-m4c-aarch64

USER root
ENV DEBIAN_FRONTEND=noninteractive \
    POETRY_VIRTUALENVS_CREATE=false \
    BSP_MSP_DIR=/opt/ax-sdk/msp_3.6.2/out

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake ninja-build git curl unzip sox libsndfile1 \
    && rm -rf /var/lib/apt/lists/*

RUN python -m pip install --no-cache-dir \
    poetry==2.4.1 cffi==2.1.1 pytest==8.4.2

WORKDIR /opt/qwen-asr-onnx
COPY pyproject.toml poetry.lock ./
RUN poetry install --with dev --no-root --no-interaction

RUN mkdir -p /opt/ax-sdk \
    && curl -fL --retry 5 \
    -o /tmp/msp_3.6.2.zip \
    https://github.com/ZHEQIUSHUI/assets/releases/download/ax_3.6.2/msp_3.6.2.zip \
    && unzip -q /tmp/msp_3.6.2.zip -d /opt/ax-sdk \
    && rm /tmp/msp_3.6.2.zip

WORKDIR /workspace