FROM registry.cn-hangzhou.aliyuncs.com/migo-dl/axengine:0.1.3-m4c-aarch64

ENV BSP_MSP_DIR=/opt/ax-sdk/msp_3.6.2/out \
    LD_LIBRARY_PATH=/soc/lib:/opt/lib

RUN apt-get update && apt-get install -y --no-install-recommends cmake \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/ax-sdk \
    && curl -fL --retry 5 \
    -o /tmp/msp_3.6.2.zip \
    https://github.com/ZHEQIUSHUI/assets/releases/download/ax_3.6.2/msp_3.6.2.zip \
    && unzip -q /tmp/msp_3.6.2.zip -d /opt/ax-sdk \
    && rm /tmp/msp_3.6.2.zip

WORKDIR /workspace
