"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from qwen_asr_onnx.protos.asr import ux_speech_pb2 as _ux_speech_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class UxSpeechStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> UxSpeechAsyncStub: ...
    StreamingRecognize: _grpc.StreamStreamMultiCallable[_ux_speech_pb2.StreamingRecognizeRequest, _ux_speech_pb2.StreamingRecognizeResponse]

@_typing.type_check_only
class UxSpeechAsyncStub(UxSpeechStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    StreamingRecognize: _aio.StreamStreamMultiCallable[_ux_speech_pb2.StreamingRecognizeRequest, _ux_speech_pb2.StreamingRecognizeResponse]  # type: ignore[assignment]

class UxSpeechServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def StreamingRecognize(
        self,
        request_iterator: _MaybeAsyncIterator[_ux_speech_pb2.StreamingRecognizeRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_ux_speech_pb2.StreamingRecognizeResponse], _abc.AsyncIterator[_ux_speech_pb2.StreamingRecognizeResponse]]: ...

def add_UxSpeechServicer_to_server(servicer: UxSpeechServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
